server:
  rootPath: /app
  maxThreads: 5
  minThreads: 5
  applicationConnectors:
  - type: h2c # http2 in clear text
    port: 8080
  requestLog:
    appenders:
    - type: console

logging:
  level: INFO
  loggers:
    ski.komoro.auto: INFO
  appenders:
  - type: console

database:
  driverClass: org.sqlite.JDBC
  user: real
  password: quite_real
  url: jdbc:sqlite:./data.db
  properties:
    encoding: UTF8
  validationQuery: "/* Health Check */ SELECT 1"
